blog/urls.py
from django.urls import path
from blog.views import *
from .feeds import LatestPostsRSSFeed


app_name = "blog"


urlpatterns = [
    path("", blog_index, name="index"),
    path("<int:pid>", blog_single, name="single"),
    path("category/<str:cat_name>", blog_index, name="category"),
    path("tag/<str:tag_name>", blog_index, name="tag"),
    path("author/<str:author_username>", blog_index, name="author"),
    path("search/", blog_search, name="search"),
    path("rss/feed", LatestPostsRSSFeed())
]

home/urls.py
from django.urls import path
from home.views import index_view, about_view, contact_view, newsletter_view

# Defining app name
app_name = "home"

urlpatterns = [
    path("", index_view, name="index"),
    path("about", about_view, name="about"),
    path("contact", contact_view, name="contact"),
    path("newsletter", newsletter_view, name="newsletter"),
]

noonpost/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from home.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap


sitemaps = {
    'static': StaticViewSitemap,
    'blog': BlogSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path("summernote/", include('django_summernote.urls')),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap"),
    path('robots.txt', include('robots.urls'))
]

handler404 = "noonpost.views.page_not_found_view"

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models


# Create your models here.
class Contact(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    subject = models.CharField(max_length=255, null=True, blank=True)
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_date']

    def __str__(self):
        return self.name


class Newsletter(models.Model):
    email = models.EmailField()

    def __str__(self):
        return self.email

home/forms.py
from django import forms
from home.models import Contact, Newsletter


class ContactForm(forms.ModelForm):
    # captcha = CaptchaField()

    class Meta:
        model = Contact
        fields = "__all__"


class NewsletterForm(forms.ModelForm):
    class Meta:
        model = Newsletter
        fields = "__all__"

home/views.py
from django.shortcuts import render, HttpResponseRedirect
from .forms import ContactForm, NewsletterForm
from django.contrib import messages
from django.conf import settings
import urllib
import json


def index_view(request):
    return render(request, "home/index.html")


def about_view(request):
    return render(request, "home/about.html")


def contact_view(request):
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            recaptcha_response = request.POST.get('g-recaptcha-response')
            url = 'https://www.google.com/recaptcha/api/siteverify'
            values = {
                'secret': settings.RECAPTCHA_PRIVATE_KEY,
                'response': recaptcha_response
            }
            data = urllib.parse.urlencode(values).encode()
            req = urllib.request.Request(url, data=data)
            response = urllib.request.urlopen(req)
            result = json.loads(response.read().decode())
            if result['success']:
                form.save()
                messages.add_message(request, messages.SUCCESS, 'Your message has been sent!')
            else:
                messages.add_message(request, messages.ERROR, "Invalid reCAPTCHA. Please try again.")
        else:
            messages.add_message(request, messages.ERROR, 'Your message was not sent!')
    form = ContactForm()
    PUBLIC_KEY = settings.RECAPTCHA_PUBLIC_KEY
    context = {'form': form, 'PUBLIC_KEY': PUBLIC_KEY}
    return render(request, "home/contact.html", context)


def newsletter_view(request):
    if request.method == "POST":
        form = NewsletterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'You subscribed to newsletter successfully.')
            return HttpResponseRedirect('/')
        else:
            messages.add_message(request, messages.ERROR, 'Your subscription was not successful.')
    else:
        return HttpResponseRedirect('/')

templates/home/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
		<aside id="colorlib-breadcrumbs">
			<div class="container">
				<div class="row">
					<div class="col-md-12 breadcrumbs text-center">
						<h2>About Me</h2>
						<p><span><a href="{% url 'home:index' %}">Home</a></span> / <span>About</span></p>
					</div>
				</div>
			</div>
		</aside>

		<div id="colorlib-container">
			<div class="container">
				<div class="row">
					<div class="col-md-6">
						<img class="img-responsive" src="{% static 'assets/images/author.jpg' %}" alt="">
					</div>
					<div class="col-md-6">
						<p>Hi! My Name is <strong>Rich</strong> Bookmarksgrove, the headline of Alphabet Village and the subline of her own road, the Line Lane. Pityful a rethoric question ran over her cheek, then she continued her way.</p>
						<blockquote>
							A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.
						</blockquote>
						<p class="first-letra">Far far away, <strong><a href="#">behind the word mountains</a></strong>, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
						<p>
							<ul class="colorlib-social-icons">
								<li><a href="https://twitter.com/CallMeELNS"><i class="icon-twitter"></i></a></li>
								<li><a href="https://github.com/EverLookNeverSee"><i class="icon-github"></i></a></li>
								<li><a href="https://www.linkedin.com/in/elns/"><i class="icon-linkedin"></i></a></li>
								<li><a href="https://t.me/EverLookNeverSee"><i class="icon-telegram"></i></a></li>
							</ul>
						</p>
					</div>
				</div>
			</div>
		</div>
		{% endblock content %}

templates/home/all_categories.html
<h2>Categories</h2>
<p class="tags">
    {% for category in categories %}
    <span><a href="{% url 'blog:category' cat_name=category.name %}"><i class="icon-tag"></i>{{ category.name }}</a></span>
    {% endfor %}
</p>

templates/home/contact.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

		<aside id="colorlib-breadcrumbs">
			<div class="container">
				<div class="row">
					<div class="col-md-12 breadcrumbs text-center">
						<h2>Contact us</h2>
						<p><span><a href="{% url 'home:index' %}">Home</a></span> / <span>Contact</span></p>
					</div>
				</div>
			</div>
		</aside>

		<div id="colorlib-container">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<h2 class="heading-2">Contact Information</h2>
						<div class="row contact-info-wrap row-pb-lg">
							<div class="col-md-3">
								<p><span><i class="icon-location-2"></i></span> 198 West 21th Street, <br> Suite 721 New York NY 10016</p>
							</div>
							<div class="col-md-3">
								<p><span><i class="icon-phone3"></i></span> <a href="tel://1234567920">+ 1235 2355 98</a></p>
							</div>
							<div class="col-md-3">
								<p><span><i class="icon-paperplane"></i></span> <a href="mailto:EverLookNeverSee@Proton.Me">EverLookNeverSee@Proton.Me</a></p>
							</div>
							<div class="col-md-3">
								<p><span><i class="icon-globe"></i></span> <a href="https://elns.info">https://elns.info</a></p>
							</div>
						</div>
					</div>
					<div class="col-md-12">
						<div class="row">
							<div class="col-md-6">
								<div id="map" class="colorlib-map"></div>
							</div>
							<div class="col-md-6">
								<h2 class="heading-2">Get In Touch</h2>
								<form action="{% url 'home:contact'%}" method="post"> {% csrf_token %}
									<div class="row form-group">
										<div class="col-md-6">
											<label for="name">Name</label>
											<input type="text" name="name" id="name" class="form-control" placeholder="Your name">
										</div>
									</div>

									<div class="row form-group">
										<div class="col-md-12">
											<label for="email">Email</label>
											<input type="email" name="email" id="email" class="form-control" placeholder="Your email address">
										</div>
									</div>

									<div class="row form-group">
										<div class="col-md-12">
											<label for="subject">Subject</label>
											<input type="text" name="subject" id="subject" class="form-control" placeholder="Your subject of this message">
										</div>
									</div>

									<div class="row form-group">
										<div class="col-md-12">
											<label for="message">Message</label>
											<textarea name="message" id="message" cols="30" rows="10" class="form-control" placeholder="Say something about us"></textarea>
										</div>
									</div>

									<div class="form-group">
										<script src='https://www.google.com/recaptcha/api.js'></script>
										<div class="g-recaptcha" data-sitekey="{{ PUBLIC_KEY }}"></div>
										<button type="submit" name="submit"  class="btn btn-primary">Send</button>
									</div>

								</form>	
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		{% endblock content %}

templates/home/footer_recent_posts.html
<h2>Recent Posts</h2>
{% for post in posts %}
<div class="f-blog">
    <a href="blog.html" class="blog-img" style="background-image: url({{ post.image.url }});">
    </a>
    <div class="desc">
        <h3><a href="{% url 'blog:single' pid=post.id %}">{{ post.title }}</a></h3>
        <p class="admin"><span>{{ post.publish_date|date:"d M Y" }}</span></p>
    </div>
</div>
{% endfor %}

templates/home/index.html
{% extends 'base.html'%}
{% load static %}
{% load humanize %}
{% load blog_tags %}
{% block content %}

		{% top_viewed_posts %}
		<div id="colorlib-container">
			<div class="container">
				<div class="row row-pb-md">
					{% home_latest_posts count=6 %}
				</div>
			</div>
		</div>
{% endblock content %}

templates/home/latest_posts.html
{% load blog_tags %}
{% load humanize %}
{% for post in posts %}
<div class="col-md-4">
    <div class="blog-entry">
        <div class="blog-img">
            <a href="#"><img src={{post.image.url}} class="img-responsive" alt="html5 bootstrap template"></a>
        </div>
        <div class="desc">
            <p>
                {% for cat in post.category.all %}
                <span class="cat"><a href="{% url 'blog:category' cat_name=cat.name %}">{{cat.name}}</a></span>{% if not forloop.last %},{% endif %}
                {% endfor %}
                <span>|</span>
                <span class="date">{{ post.publish_date|naturaltime }}</span>
                <span>|</span>
                <span class="pos">By <a href="{% url 'blog:author' author_username=post.author.username %}">{{ post.author}}</a></span>
                <span>|</span>
                <span class="pos">{{ post.count_views }} views</span>
            </p>
            <h2><a href="{% url 'blog:single' pid=post.id %}">{{ post.title }}</a></h2>
            <p>{{ post.content|truncatewords:30|safe }}</p>
        </div>
    </div>
</div>
{% endfor %}

templates/home/top_viewed_posts.html
{% load humanize %}
<aside id="colorlib-hero">
			<div class="flexslider">
				<ul class="slides">
					{% for post in posts %}
			   	<li style="background-image: url({{ post.image.url }});">
			   		<div class="overlay"></div>
			   		<div class="container">
			   			<div class="row">
				   			<div class="col-md-6 col-md-pull-3 col-sm-12 col-xs-12 col-md-offset-3 slider-text">
				   				<div class="slider-text-inner">
				   					<div class="desc">
				   						<p>
												{% for cat in post.category.all %}
												<span class="cat"><a href="{% url 'blog:category' cat_name=cat.name %}">{{ cat.name }}</a></span>{% if not forloop.last %},{% endif %}
												{% endfor %}
												<span>|</span>
												<span class="date">{{ post.publish_date|naturaltime }}</span>
												<span>|</span>
												<span class="pos">By <a href="{% url 'blog:author' author_username=post.author.username %}">{{ post.author }}</a></span>
												<span>|</span>
												<span class="pos">{{ post.count_views }} views</span>
											</p>
					   					<h1><a href="{% url 'blog:single' pid=post.id %}">{{ post.title }}</a></h1>
				   					</div>
				   				</div>
				   			</div>
				   		</div>
			   		</div>
			   	</li>
					{% endfor %}
			  	</ul>
		  	</div>
		</aside>