accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from accounts.views import login_view, logout_view, signup_view, EmailValidationOnForgotPassword


# Defining appname
app_name = "accounts"

urlpatterns = [
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("signup/", signup_view, name="signup"),

    path("password-reset/", auth_views.PasswordResetView.as_view(
        template_name="accounts/password_reset.html",
        email_template_name="accounts/password_reset_email.html",
        success_url=reverse_lazy("accounts:password_reset_done"),
        form_class=EmailValidationOnForgotPassword
    ), name="password_reset"),
    path("password-reset/done/", auth_views.PasswordResetDoneView.as_view(
        template_name="accounts/password_reset_done.html",
    ), name="password_reset_done"),
    path("password-reset-confirm/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(
        template_name="accounts/password_reset_confirm.html",
        success_url=reverse_lazy("accounts:password_reset_complete")
    ), name="password_reset_confirm"),
    path("password-reset/complete/", auth_views.PasswordResetCompleteView.as_view(
        template_name="accounts/password_reset_complete.html",
        title="Password reset completed."
    ), name="password_reset_complete"),
]

blog/urls.py
from django.urls import path
from blog.views import *
from .feeds import LatestPostsRSSFeed


app_name = "blog"


urlpatterns = [
    path("", blog_index, name="index"),
    path("<int:pid>", blog_single, name="single"),
    path("category/<str:cat_name>", blog_index, name="category"),
    path("tag/<str:tag_name>", blog_index, name="tag"),
    path("author/<str:author_username>", blog_index, name="author"),
    path("search/", blog_search, name="search"),
    path("rss/feed", LatestPostsRSSFeed())
]

noonpost/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from home.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap


sitemaps = {
    'static': StaticViewSitemap,
    'blog': BlogSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path("summernote/", include('django_summernote.urls')),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap"),
    path('robots.txt', include('robots.urls'))
]

handler404 = "noonpost.views.page_not_found_view"

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


class UserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)

    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Username or Email'}), label='Username or Email')
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                 'placeholder': 'Password'}))
    remember_me = forms.BooleanField(required=False, widget=forms.CheckboxInput(attrs={'class': 'form-check-input'}))


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={
            'class': 'form-control',
            'placeholder': 'Email'
        }),
        label='Email')

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

accounts/views.py
from django import forms
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.decorators import login_required
from accounts.forms import UserLoginForm, UserRegisterForm
from django.contrib.auth import login, authenticate, logout, get_user_model


def login_view(request):
    if not request.user.is_authenticated:
        if request.method == "POST":
            form = UserLoginForm(request=request, data=request.POST)
            if form.is_valid():
                username = form.cleaned_data.get('username')
                password = form.cleaned_data.get('password')
                remember = form.cleaned_data.get('remember_me')
                user = authenticate(request, username=username, password=password)
                if user is not None:
                    login(request, user)
                    messages.add_message(request, messages.SUCCESS, 'You are now logged in!')
                    if not remember:
                        request.session.set_expiry(0)
                    return redirect('/')
            else:
                messages.add_message(request, messages.ERROR, 'Your entered information was wrong!')
                return render(request, 'accounts/login.html', {'form': form})
        elif request.method == "GET":
            form = UserLoginForm()
            context = {'form': form}
            return render(request, 'accounts/login.html', context)
    else:
        messages.add_message(request, messages.WARNING, "You are already logged In.")
        return redirect('/')


@login_required(login_url='/accounts/login')
def logout_view(request):
    logout(request)
    messages.add_message(request, messages.SUCCESS, 'You are now logged out!')
    return redirect('/')


def signup_view(request):
    if not request.user.is_authenticated:
        if request.method == "POST":
            form = UserRegisterForm(request.POST)
            if form.is_valid():
                form.save()
                messages.add_message(request, messages.SUCCESS, 'You are now registered!')
                return redirect('/')
            else:
                messages.add_message(request, messages.ERROR, 'Your entered information was wrong!')
        form = UserRegisterForm()
        context = {'form': form}
        return render(request, 'accounts/signup.html', context)
    else:
        messages.add_message(request, messages.WARNING, 'You are already logged in!')
        return redirect('/')


class EmailValidationOnForgotPassword(PasswordResetForm):
    def clean_email(self):
        email = self.cleaned_data.get('email')
        User = get_user_model()
        if not User.objects.filter(email__iexact=email, is_active=True).exists():
            raise forms.ValidationError("There is no user registered with this email address!")
        return email

templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}
<form action="{% url 'accounts:login'%}", method="post">{% csrf_token %}
    <div class="form-inline">
        <label for="username">Username or Email</label>
        <input type="text" class="form-control" id="username" name="username" placeholder="Username">
    </div>
    <div class="form-inline">
        <label for="password">Password</label>
        <input type="password" class="form-control" id="password" name="password" placeholder="Password">
    </div>
    <div class="form-inline">
        <label>Remember me</label>
        <input type="checkbox" class="form-control"  name="remember_me" placeholder="Password">
    </div>
    <div class="form-inline">
        <a href="{% url 'accounts:password_reset' %}">Forgot password?</a>
    </div>
    <button type="submit" class="btn btn-primary">Login</button>
</form>
{% endblock content%}

templates/accounts/password_reset.html
{% extends "base.html" %}
{% block content %}
    <h3>Forgotten your password?</h3>
    <p>Enter your e-mail address to obtain a new password.</p>

    <form action="." method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <p><input type="submit" value="Send e-mail"></p>
    </form>
{% endblock %}

templates/accounts/password_reset_complete.html
{% extends 'base.html' %}
{% block content %}
<div>
    <h3>Password set</h3>
    <h4>Your password has been set. You can <a href="{% url 'accounts:login' %}">log in now</a></h4>
</div>
{% endblock content %}

templates/accounts/password_reset_confirm.html
{% extends "base.html" %}

{% block content %}
<h3>Reset your password</h3>

{% if validlink %}
<p>Please enter your new password twice:</p>
<form action="." method="post">
{% csrf_token %}
    {{ form.as_p }}

<p><input type="submit" value="Change my password" /></p>
</form>
{% else %}
<p>The password reset link was invalid, possibly because it has
already been used. Please request a new password reset.</p>
{% endif %}
{% endblock %}

templates/accounts/password_reset_done.html
{% extends "base.html" %}

{% block content %}
{% csrf_token %}
<div>
    <h1>Reset your password</h1>
    <p>We've emailed you instructions for setting your password.</p>
    <p>If you don't receive an email, please make sure you've entered the
address you registered with.</p>
</div>
{% endblock %}

templates/accounts/password_reset_email.html
{% autoescape off %}
To initiate the password reset process for your {{ user.email }} Django Registration/Login App Account,
click the link below:

   {{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser window instead.

Sincerely,

NoonPost Administration
{% endautoescape %}