blog/urls.py
from django.urls import path
from blog.views import *
from .feeds import LatestPostsRSSFeed


app_name = "blog"


urlpatterns = [
    path("", blog_index, name="index"),
    path("<int:pid>", blog_single, name="single"),
    path("category/<str:cat_name>", blog_index, name="category"),
    path("tag/<str:tag_name>", blog_index, name="tag"),
    path("author/<str:author_username>", blog_index, name="author"),
    path("search/", blog_search, name="search"),
    path("rss/feed", LatestPostsRSSFeed())
]

home/urls.py
from django.urls import path
from home.views import index_view, about_view, contact_view, newsletter_view

# Defining app name
app_name = "home"

urlpatterns = [
    path("", index_view, name="index"),
    path("about", about_view, name="about"),
    path("contact", contact_view, name="contact"),
    path("newsletter", newsletter_view, name="newsletter"),
]

noonpost/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from home.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap


sitemaps = {
    'static': StaticViewSitemap,
    'blog': BlogSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path("summernote/", include('django_summernote.urls')),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap"),
    path('robots.txt', include('robots.urls'))
]

handler404 = "noonpost.views.page_not_found_view"

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from taggit.managers import TaggableManager



class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    image = models.ImageField(upload_to="blog/", default="blog/default.jpg")
    category = models.ManyToManyField(Category)
    tags = TaggableManager()
    count_views = models.PositiveIntegerField(default=0)
    ok_to_publish = models.BooleanField(default=False)
    login_required = models.BooleanField(default=False)
    publish_date = models.DateTimeField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']
        verbose_name = "Post"
        verbose_name_plural = "Posts"

    def __str__(self):
        return f"{self.title}"

    def get_absolute_url(self):
        return reverse("blog:single", kwargs={"pid": self.id})


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    is_approved = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Comment'
        verbose_name_plural = 'Comments'

    def __str__(self):
        return f"{self.name} - {self.subject}"

blog/forms.py
from django import forms
from blog.models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'subject', 'message']

blog/views.py
import json
import urllib
from django.urls import reverse
from django.conf import settings
from django.utils import timezone
from blog.forms import CommentForm
from django.contrib import messages
from blog.models import Post, Comment
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q


def blog_index(request, **kwargs):
    posts = Post.objects.filter(ok_to_publish=True, publish_date__lte=timezone.now()).order_by("-publish_date")
    if kwargs.get("cat_name") is not None:
        posts = posts.filter(category__name=kwargs["cat_name"], ok_to_publish=True)
    if kwargs.get("author_username") is not None:
        posts = posts.filter(author__username=kwargs["author_username"], ok_to_publish=True)
    if kwargs.get("tag_name") is not None:
        posts = posts.filter(tags__name__in=[kwargs["tag_name"]], ok_to_publish=True)
    posts = Paginator(posts, 6)
    try:
        page_number = request.GET.get("page")
        posts = posts.page(page_number)
    except PageNotAnInteger:
        posts = posts.page(1)
    except EmptyPage:
        posts = posts.page(1)
    context = {"posts": posts}
    return render(request, "blog/blog-home.html", context)


def increment_views(pid):
    post = get_object_or_404(Post, id=pid)
    post.count_views += 1
    post.save()


def get_previous_next_posts(pid):
    post = get_object_or_404(Post, id=pid)
    previous_post = Post.objects.filter(publish_date__lte=timezone.now()).order_by('-publish_date').filter(
        publish_date__lte=post.publish_date).exclude(id=pid).first()
    next_post = Post.objects.filter(publish_date__lte=timezone.now()).order_by('-publish_date').filter(
        publish_date__gte=post.publish_date).exclude(id=pid).last()
    return previous_post, next_post


def blog_single(request, pid):
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            recaptcha_response = request.POST.get('g-recaptcha-response')
            url = 'https://www.google.com/recaptcha/api/siteverify'
            values = {
                'secret': settings.RECAPTCHA_PRIVATE_KEY,
                'response': recaptcha_response
            }
            data = urllib.parse.urlencode(values).encode()
            req = urllib.request.Request(url, data=data)
            response = urllib.request.urlopen(req)
            result = json.loads(response.read().decode())
            if not result['success']:
                messages.add_message(request, messages.ERROR, "Invalid reCAPTCHA. Please try again.")
            elif result['success']:
                new_form = form.save(commit=False)
                new_form.post = get_object_or_404(Post, id=pid)
                new_form.save()
                messages.add_message(request, messages.SUCCESS, "Comment added successfully.")
        else:
            messages.add_message(request, messages.ERROR, "Error adding comment!")
    post = get_object_or_404(Post, id=pid, ok_to_publish=True, publish_date__lte=timezone.now())
    comments = Comment.objects.filter(post=post.id, is_approved=True)
    increment_views(pid)
    form = CommentForm()
    PUBLIC_KEY = settings.RECAPTCHA_PUBLIC_KEY
    context = {"post": post, "comments": comments, "form": form, 'PUBLIC_KEY': PUBLIC_KEY}
    # previous_post, next_post = get_previous_next_posts(pid)
    # if previous_post:
    #     context["previous_post"] = previous_post
    # if next_post:
    #     context["next_post"] = next_post
    if post.login_required is False:
        return render(request, "blog/blog-single.html", context)
    else:
        if request.user.is_authenticated:
            return render(request, "blog/blog-single.html", context)
        else:
            return HttpResponseRedirect(reverse("accounts:login"))


def blog_search(request):
    posts = Post.objects.filter(ok_to_publish=True, publish_date__lte=timezone.now()).order_by('-publish_date')
    if request.method == "GET":
        if s := request.GET.get("s"):
            posts = posts.filter(Q(title__icontains=s) | Q(content__icontains=s))
    context = {"posts": posts}
    return render(request, "blog/blog-home.html", context)

templates/blog/blog-home.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load blog_tags %}
{% block content %}
		<aside id="colorlib-breadcrumbs">
			<div class="container">
				<div class="row">
					<div class="col-md-12 breadcrumbs text-center">
						<h2>Read our blog</h2>
						<p><span><a href="{% url 'home:index' %}">Home</a></span> / <span>Blog</span></p>
					</div>
				</div>
			</div>
		</aside>

		<div id="colorlib-container">
			<div class="container">
				<div class="row row-pb-md">
					<!---------------------------------------------------------------->
					{% for post in posts %}
					<div class="col-md-4">
						<div class="blog-entry">
							<div class="blog-img">
								<a href="blog.html"><img src="{{ post.image.url }}" class="img-responsive" alt="html5 bootstrap template"></a>
							</div>
							<div class="desc">
								<p>
									{% for cat in post.category.all %}
									<span class="cat"><a href="{% url 'blog:category' cat_name=cat.name %}">{{ cat.name }}</a></span>{% if not forloop.last %},{% endif %}
									{% endfor %}
									<span>|</span>
									<span class="date">{{ post.publish_date|naturaltime }}</span>
									<span>|</span>
									<span class="pos">By <a href="{% url 'blog:author' author_username=post.author.username %}">{{ post.author }}</a></span>
									<span>|</span>
									<span class="pos">{{ post.count_views }} views</span>
								</p>
								<h2><a href="{% url 'blog:single' pid=post.id %}">{{ post.title }}</a></h2>
								<p>{{ post.content|truncatewords:30|safe }}</p>
							</div>
						</div>
					</div>
					{% endfor %}
					<!------------------------------------------------------------------------>
				<div class="row">
					<div class="col-md-12 text-center">
						<ul class="pagination">
							{% if posts.has_previous %}
							<li><a href="?page={{posts.previous_page_number}}">&laquo;</a></li>
							{% endif %}
							{% for i in posts.paginator.page_range %}
							{% if posts.number == i %}
							<li class="active"><a href="?page={{i}}">{{ i }}</a></li>
							{% else %}
							<li class="inactive"><a href="?page={{i}}">{{ i }}</a></li>
							{% endif %}
							{% endfor %}
							{% if posts.has_next %}
							<li><a href="?page={{posts.next_page_number}}">&raquo;</a></li>
							{% endif %}
						</ul>
					</div>
				</div>
			</div>
		</div>
{% endblock content %}

templates/blog/blog-single.html
{% extends 'base.html' %}
{% load static %}
{% load blog_tags %}
{% load humanize %}
{% block content %}
		<aside id="colorlib-breadcrumbs">
			<div class="container">
				<div class="row">
					<div class="col-md-12 breadcrumbs text-center">
						<h2>Blog post detail</h2>
						<p><span><a href="{% url 'home:index' %}">Home</a></span> / <span><a href="{% url 'blog:index' %}">Blog </a></span> / <span>Blog Single</span></p>
					</div>
				</div>
			</div>
		</aside>

		<div id="colorlib-container">
			<div class="container">
				<div class="row">
					<div class="col-md-9 content">
						<div class="row row-pb-lg">
							<div class="col-md-12">
								<div class="blog-entry">
									<div class="blog-img blog-detail">
										<img src="{{ post.image.url }}" class="img-responsive" alt="html5 bootstrap template">
									</div>
									<div class="desc">
										<p>
											{% for cat in post.category.all %}
											<span class="cat"><a href="{% url 'blog:category' cat_name=cat.name %}">{{ cat.name }}</a></span>{% if not forloop.last %},{% endif %}
											{% endfor %}
											<span>|</span>
											<span class="date">{{ post.publish_date|naturaltime }}</span>
											<span>|</span>
											<span class="pos">By <a href="{% url 'blog:author' author_username=post.author.username %}">{{ post.author.username }}</a></span>
											<span>|</span>
											<span class="pos">{{ post.count_views }} views</span>
										</p>
										<h2>{{ post.title }}</h2>
										<p>{{ post.content|safe }}</p>
									</div>
								</div>
							</div>
						</div>
						<div class="row row-pb-lg">
							<div class="col-md-12">
								<h2 class="heading-2">{% comments_count pid=post.id %} Comments</h2>
								{% for comment in comments %}
								<div class="review">
						   			<div class="user-img" style="background-image: url({% static 'assets/images/user.png' %})"></div>
						   				<div class="desc">
						   					<h4>
						   						<span class="text-left">{{ comment.name }}</span>
						   						<span class="text-right">{{ comment.created_at|naturalday }}</span>
											</h4>
											<p>{{ comment.message }}</p>
						   			</div>
								</div>
								{% endfor %}
							</div>
						</div>
						<div class="row">
							<div class="col-md-12">
								<h2 class="heading-2">Say something</h2>
								<form action="{% url 'blog:single' pid=post.id %}", method="post">{% csrf_token %}
									<!--------------------------------------------------------------------------------->
									{% if request.user.is_authenticated %}
									<div class="row form-group">
										<div class="col-md-6">
											<input type="hidden" name="name" value="{{ request.user.get_full_name }}">
										</div>
									</div>

									<div class="row form-group">
										<div class="col-md-12">
											<input type="hidden" name="email" value="{{ request.user.email }}">
										</div>
									</div>
									{% else %}
									<!--------------------------------------------------------------------------------->
									<div class="row form-group">
										<div class="col-md-6">
											<input type="text" id="name" name="name" class="form-control" placeholder="Fullname">
										</div>
									</div>

									<div class="row form-group">
										<div class="col-md-12">
											<input type="email" name="email" class="form-control" placeholder="Your email address">
										</div>
									</div>
									{% endif %}
									<!--------------------------------------------------------------------------------->
									<div class="row form-group">
										<div class="col-md-12">
											<!-- <label for="subject">Subject</label> -->
											<input type="text" id="subject" name="subject" class="form-control" placeholder="Your subject of this message">
										</div>
									</div>

									<div class="row form-group">
										<div class="col-md-12">
											<!-- <label for="message">Message</label> -->
											<textarea name="message" id="message" cols="30" rows="10" class="form-control" placeholder="Say something about us"></textarea>
										</div>
									</div>
									<div class="form-group">
										<script src='https://www.google.com/recaptcha/api.js'></script>
										<div class="g-recaptcha" data-sitekey="{{ PUBLIC_KEY }}"></div>
										<input type="submit" value="Post Comment" class="btn btn-primary">
									</div>
								</form>	
							</div>
						</div>
					</div>
					<div class="col-md-3">
						<div class="sidebar">
							<div class="side">
								<div class="form-group">
									<form action="{% url 'blog:search' %}" method="get">
										<input type="text" name="s" class="form-control" id="search" placeholder="Search in posts">
										<button type="submit" class="btn btn-primary"><i class="icon-search3"></i></button>
									</form>
								</div>
							</div>
							<div class="side">
								<!----------------------------------------------------------------->
								{% posts_categories %}
								<!----------------------------------------------------------------->
							</div>
							<div class="side">
								<h2 class="sidebar-heading">Instagram</h2>
								<div class="instagram-entry">
									<a href="https://instagram.com/" class="instagram text-center" style="background-image: url({% static 'assets/images/gallery-1.jpg' %});">
									</a>
									<a href="https://instagram.com/" class="instagram text-center" style="background-image: url({% static 'assets/images/gallery-2.jpg' %});">
									</a>
									<a href="https://instagram.com/" class="instagram text-center" style="background-image: url({% static 'assets/images/gallery-3.jpg' %});">
									</a>
									<a href="https://instagram.com/" class="instagram text-center" style="background-image: url({% static 'assets/images/gallery-4.jpg' %});">
									</a>
									<a href="https://instagram.com/" class="instagram text-center" style="background-image: url({% static 'assets/images/gallery-5.jpg' %});">
									</a>
									<a href="https://instagram.com/" class="instagram text-center" style="background-image: url({% static 'assets/images/gallery-6.jpg' %});">
									</a>
									<a href="https://instagram.com/" class="instagram text-center" style="background-image: url({% static 'assets/images/gallery-7.jpg' %});">
									</a>
									<a href="https://instagram.com/" class="instagram text-center" style="background-image: url({% static 'assets/images/gallery-8.jpg' %});">
									</a>
								</div>
							</div>
							<div class="side">
								<div class="form-group">
									<form action="{% url 'home:newsletter' %}" method="post">{% csrf_token %}
										<input type="email" name="email" class="form-control form-email text-center" id="email" placeholder="Enter your email">
										<button type="submit" class="btn btn-primary btn-subscribe">Subscribe to newsletter</button>
									</form>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

{% endblock content %}

templates/blog/posts-categories.html
<h2 class="sidebar-heading">Categories</h2>
<p>
<ul class="category">
    {% for name, count in categories.items %}
    <li><a href="{% url 'blog:category' cat_name=name %}"><i class="icon-check"></i>{{ name }}:  {{ count }} posts</a></li>
    {% endfor %}
</ul>
</p>