accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from accounts.views import login_view, logout_view, signup_view, EmailValidationOnForgotPassword


# Defining appname
app_name = "accounts"

urlpatterns = [
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("signup/", signup_view, name="signup"),

    path("password-reset/", auth_views.PasswordResetView.as_view(
        template_name="accounts/password_reset.html",
        email_template_name="accounts/password_reset_email.html",
        success_url=reverse_lazy("accounts:password_reset_done"),
        form_class=EmailValidationOnForgotPassword
    ), name="password_reset"),
    path("password-reset/done/", auth_views.PasswordResetDoneView.as_view(
        template_name="accounts/password_reset_done.html",
    ), name="password_reset_done"),
    path("password-reset-confirm/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(
        template_name="accounts/password_reset_confirm.html",
        success_url=reverse_lazy("accounts:password_reset_complete")
    ), name="password_reset_confirm"),
    path("password-reset/complete/", auth_views.PasswordResetCompleteView.as_view(
        template_name="accounts/password_reset_complete.html",
        title="Password reset completed."
    ), name="password_reset_complete"),
]

blog/urls.py
from django.urls import path
from blog.views import *
from .feeds import LatestPostsRSSFeed


app_name = "blog"


urlpatterns = [
    path("", blog_index, name="index"),
    path("<int:pid>", blog_single, name="single"),
    path("category/<str:cat_name>", blog_index, name="category"),
    path("tag/<str:tag_name>", blog_index, name="tag"),
    path("author/<str:author_username>", blog_index, name="author"),
    path("search/", blog_search, name="search"),
    path("rss/feed", LatestPostsRSSFeed())
]

home/urls.py
from django.urls import path
from home.views import index_view, about_view, contact_view, newsletter_view

# Defining app name
app_name = "home"

urlpatterns = [
    path("", index_view, name="index"),
    path("about", about_view, name="about"),
    path("contact", contact_view, name="contact"),
    path("newsletter", newsletter_view, name="newsletter"),
]

noonpost/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from home.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap


sitemaps = {
    'static': StaticViewSitemap,
    'blog': BlogSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path("summernote/", include('django_summernote.urls')),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap"),
    path('robots.txt', include('robots.urls'))
]

handler404 = "noonpost.views.page_not_found_view"

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
{% load compress %}
{% load humanize %}
{% load blog_tags %}
<!DOCTYPE HTML>
<html>
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>NoonPost</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Personal blog platform" />
	<meta name="keywords" content="django, python, blog, personal, backend" />
	<meta name="author" content="Milad Sadeghi DM" />



	<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,700" rel="stylesheet">
		<link rel="shortcut icon" href="{% static 'assets/images/favicon.ico' %}" />
	{% compress css %}
	<!-- Animate.css -->
	<link rel="stylesheet" href="{% static 'assets/css/animate.css' %}">
	<!-- Icomoon Icon Fonts-->
	<link rel="stylesheet" href="{% static 'assets/css/icomoon.css' %}">
	<!-- Bootstrap  -->
	<link rel="stylesheet" href="{% static 'assets/css/bootstrap.css' %}">

	<!-- Magnific Popup -->
	<link rel="stylesheet" href="{% static 'assets/css/magnific-popup.css' %}">

	<!-- Flexslider  -->
	<link rel="stylesheet" href="{% static 'assets/css/flexslider.css' %}">

	<!-- Owl Carousel -->
	<link rel="stylesheet" href="{% static 'assets/css/owl.carousel.min.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/owl.theme.default.min.css' %}">

	<!-- Theme style  -->
	<link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
		{% endcompress %}

		{% compress js %}
	<script src="{% static 'assets/js/modernizr-2.6.2.min.js' %}"></script>
	<script src="{% static 'assets/js/respond.min.js' %}"></script>
	{% endcompress %}


	</head>
	<body>

	<div class="colorlib-loader"></div>

	<div id="page">
		<nav class="colorlib-nav" role="navigation">
			<div class="top-menu">
				<div class="container">
					<div class="row">
						<div class="col-xs-2">
							<div id="colorlib-logo"><a href="{% url 'home:index' %}">NoonPost</a></div>
						</div>
						<div class="col-xs-10 text-right menu-1">
							<ul>
								<li><a href="{% url 'home:index' %}">Home</a></li>
								<li><a href="{% url 'blog:index' %}">Blog</a></li>
								<li><a href="{% url 'home:about' %}">About Me</a></li>
								<li><a href="{% url 'home:contact' %}">Contact</a></li>
								{% if request.user.is_authenticated %}
								<li class="active"><a href="#">Loggid in as {{ request.user.username}}</a></li>
								<li class="active"><a href="{% url 'accounts:logout' %}">Logout</a></li>
								{% else %}
								<li class="active"><a href="{% url 'accounts:login' %}">Login</a></li>
								<li class="active"><a href="{% url 'accounts:signup' %}">SignUp</a></li>
								{% endif %}
							</ul>
						</div>
					</div>
				</div>
			</div>
		</nav>
		<div>
		{% if messages %}
			{% for message in messages %}
				<div class="alert alert-{{ message.tags }}">
					{{ message.message }}
				</div>
			{% endfor %}
		{% endif %}
		</div>
        {% block content %}

        {% endblock content%}

        <div id="colorlib-instagram">
			<div class="row">
				<div class="col-md-12 col-md-offset-0 colorlib-heading text-center">
					<h2>Instagram</h2>
				</div>
			</div>
			<div class="row">
				<div class="instagram-entry">
					<a href="https://instagram.com/" class="instagram text-center" style="background-image: url({% static 'assets/images/gallery-1.jpg' %});">
					</a>
					<a href="https://instagram.com/" class="instagram text-center" style="background-image: url({% static 'assets/images/gallery-2.jpg' %});">
					</a>
					<a href="https://instagram.com/" class="instagram text-center" style="background-image: url({% static 'assets/images/gallery-3.jpg' %});">
					</a>
					<a href="https://instagram.com/" class="instagram text-center" style="background-image: url({% static 'assets/images/gallery-4.jpg' %});">
					</a>
					<a href="https://instagram.com/" class="instagram text-center" style="background-image: url({% static 'assets/images/gallery-5.jpg' %});">
					</a>
					<a href="https://instagram.com/" class="instagram text-center" style="background-image: url({% static 'assets/images/gallery-6.jpg' %});">
					</a>
					<a href="https://instagram.com/" class="instagram text-center" style="background-image: url({% static 'assets/images/gallery-7.jpg' %});">
					</a>
					<a href="https://instagram.com/" class="instagram text-center" style="background-image: url({% static 'assets/images/gallery-8.jpg' %});">
					</a>
				</div>
			</div>
		</div>
		<footer id="colorlib-footer" role="contentinfo">
			<div class="container">
				<div class="row row-pb-md">
					<div class="col-md-3">
						<h2>Navigational</h2>
						<p>
							<ul class="colorlib-footer-links">
								<li><a href="{% url 'home:index' %}"><i class="icon-check"></i> Home</a></li>
								<li><a href="{% url 'blog:index'%}"><i class="icon-check"></i> Blog</a></li>
								<li><a href="{% url 'home:about' %}"><i class="icon-check"></i> About Me</a></li>
								<li><a href="{% url 'home:contact' %}"><i class="icon-check"></i> Contact</a></li>
							</ul>
						</p>
					</div>
					<div class="col-md-3">
						{% footer_recent_posts %}
					</div>
					<div class="col-md-3">
						{% all_categories %}
					</div>
				</div>
				<div class="row">
					<div class="col-md-12">
						<p>
							<small class="block"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></small>
							<small class="block">Demo Images: <a href="http://unsplash.co/" target="_blank">Unsplash</a></small>
						</p>
					</div>
				</div>
			</div>
		</footer>
	</div>

	<div class="gototop js-top">
		<a href="#" class="js-gotop"><i class="icon-arrow-up2"></i></a>
	</div>

	{% compress js %}
	<!-- jQuery -->
	<script src="{% static 'assets/js/jquery.min.js' %}"></script>
	<!-- jQuery Easing -->
	<script src="{% static 'assets/js/jquery.easing.1.3.js' %}"></script>
	<!-- Bootstrap -->
	<script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
	<!-- Waypoints -->
	<script src="{% static 'assets/js/jquery.waypoints.min.js' %}"></script>
	<!-- Flexslider -->
	<script src="{% static 'assets/js/jquery.flexslider-min.js' %}"></script>
	<!-- Owl carousel -->
	<script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>
	<!-- Magnific Popup -->
	<script src="{% static 'assets/js/jquery.magnific-popup.min.js' %}"></script>
	<script src="{% static 'assets/js/magnific-popup-options.js' %}"></script>
	<!-- Main -->
	<script src="{% static 'assets/js/main.js' %}"></script>
	{% endcompress %}

	</body>
</html>

templates/not_found.html
{% load static %}
{% load compress %}

<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

	<title>404 HTML Template by Colorlib</title>

	<!-- Google font -->
	<link href="https://fonts.googleapis.com/css?family=Montserrat:200,400,700" rel="stylesheet">

	<!-- Custom stlylesheet -->
	{% compress css %}
	<link type="text/css" rel="stylesheet" href="{% static 'assets/css/style.css' %}" />
	{% endcompress %}
	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
	{% compress js %}
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
	{% endcompress %}

</head>

<body>

	<div id="notfound">
		<div class="notfound">
			<div class="notfound-404">
				<h1>Oops!</h1>
				<h2>404 - The Page can't be found</h2>
			</div>
			<a href="{% url 'home:index' %}">Go TO Homepage</a>
		</div>
	</div>

</body><!-- This templates was made by Colorlib (https://colorlib.com) -->

</html>